### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'enum' when creating sensor_oven_water_tank (1.0.5b11)

### ISSUE THREAD

**Issue by stefanhintermayr** [chris-mc1/homeconnect_local_hass#407]
## Bug Report

**Integration version:** 1.0.5b11 (Beta)
**Home Assistant version:** 2026.6.1
**Affected device:** Oven (water tank / steam function)

## Description

After updating to 1.0.5b11, the integration fails to create the `sensor_oven_water_tank` entity with an AttributeError. The entity setup appears to assume `entity_description.enum` is always present, but for my oven it comes back as `None`.

## Error Log
ERROR (MainThread) [custom_components.homeconnect_ws.helpers] Failed to create Entity sensor_oven_water_tank

Traceback (most recent call last):

File "/config/custom_components/homeconnect_ws/helpers.py", line 40, in create_entities

entity = entity_class(

entity_description=entity_description, runtime_data=runtime_data

)

File "/config/custom_components/homeconnect_ws/sensor.py", line 57, in init

if self._entity.enum:

^^^^^^^^^^^^^^^^^

AttributeError: 'NoneType' object has no attribute 'enum'

## Expected behavior

The entity should either be skipped gracefully if `enum` data is unavailable for this appliance, or the sensor class should handle `None` without raising.

## Suggested fix

Add a None-check before accessing `.enum`, e.g.:

```python
if self._entity is not None and self._entity.enum:
```

Happy to provide diagnostics or test a fix — appliance is a Bosch/Siemens oven with steam/water tank function.

### Before submitting a bug report, please follow these troubleshooting steps

- [x] I have tried the latest beta release of Home Connect Local.
- [x] I have checked that I can perform the same action through the HomeConnect App.
- [x] I have checked the [open issues](https://github.com/chris-mc1/homeconnect_local_hass/issues) to ensure my issue isn't a duplicate.

### Version of Home Connect Local

1.0.5b11

### Version of Home Assistant

2026.6.1

### Diagnostics information

No diagnostics available - entity creation fails immediately on integration reload, see error log below.

### Debug logs

```txt
ERROR (MainThread) [custom_components.homeconnect_ws.helpers] Failed to create Entity sensor_oven_water_tank
Traceback (most recent call last):
  File "/config/custom_components/homeconnect_ws/helpers.py", line 40, in create_entities
    entity = entity_class(
        entity_description=entity_description, runtime_data=runtime_data
    )
  File "/config/custom_components/homeconnect_ws/sensor.py", line 57, in __init__
    if self._entity.enum:
       ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'enum'
```

**Comment by Beckspirat85** [comment]
Same here on 1.0.5b11 with a Siemens HN678G4S6 (oven with steam boost function
and water tank).

Identical traceback, occurs four times on every integration reload.
Home Assistant 2026.8.0, appliance firmware 3.4.4.0.

The device description may explain why `enum` is None. Both water tank statuses
are declared as plain booleans, without an `enumerationType` attribute:

    <status access="read" available="true" refCID="01" refDID="00" uid="1005"/>   
    <status access="read" available="true" refCID="01" refDID="00" uid="1006"/>   

For comparison, a status that does work carries the attribute:

    <status access="read" available="true" enumerationType="0201" refCID="03" refDID="80" uid="020F"/>

From the feature mapping:

    <feature refUID="1005">Cooking.Oven.Status.WaterTankEmpty</feature>
    <feature refUID="1006">Cooking.Oven.Status.WaterTankUnplugged</feature>

So these look like they should be created as binary_sensor rather than sensor —
a None-check would silence the error but drop the entity entirely.

Happy to attach the full device profile XMLs and config entry diagnostics.

**Comment by Beckspirat85** [comment]
Still failing on 1.0.5 (final), same appliance: Siemens HN678G4S6 oven with steam boost function and water tank.

The entity is now created instead of failing during setup, but it crashes on the first state write. The same AttributeError has just moved from `sensor.py:57` to `sensor.py:65`:

    ERROR (MainThread) [homeassistant.components.sensor]
    Error adding entity sensor.kuche_siemens_oven_wassertank for domain sensor with platform homeconnect_ws
    Traceback (most recent call last):
      File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 725, in _async_add_entities
        await self._async_add_entity(
            entity, False, entity_registry, config_subentry_id
        )
      File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1127, in _async_add_entity
        await entity.add_to_platform_finish()
      File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1446, in add_to_platform_finish
        self.async_write_ha_state()
      File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1061, in async_write_ha_state
        self._async_write_ha_state()
      File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1213, in _async_write_ha_state
        ) = self.__async_calculate_state()
      File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1119, in __async_calculate_state
        state = self._stringify_state(available)
      File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1067, in _stringify_state
        if (state := self.state) is None:
      File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 606, in state
        value = self.native_value
      File "/config/custom_components/homeconnect_ws/sensor.py", line 65, in native_value
        if self._entity.value is None:
           ^^^^^^^^^^^^^^^^^^
    AttributeError: 'NoneType' object has no attribute 'value'

Entity: `sensor.kuche_siemens_oven_wassertank`

`self._entity` itself is None, so guarding `.enum` and `.value` individually won't fix it, the underlying feature lookup fails. As noted in my earlier comment, both water tank statuses are declared without an `enumerationType` attribute in the device description:

    <status access="read" available="true" refCID="01" refDID="00" uid="1005"/>   
    <status access="read" available="true" refCID="01" refDID="00" uid="1006"/>   

For comparison, a status that does work carries the attribute:

    <status access="read" available="true" enumerationType="0201" refCID="03" refDID="80" uid="020F"/>

Feature mapping:

    <feature refUID="1005">Cooking.Oven.Status.WaterTankEmpty</feature>
    <feature refUID="1006">Cooking.Oven.Status.WaterTankUnplugged</feature>

These are plain booleans and should probably be created as `binary_sensor` rather than `sensor`.

Integration 1.0.5 (final), appliance firmware 3.4.4.0. Reopening as the error persists.
